export const PREDEFINED_SKILLS = [
    'Passing',
    'Offence',
    'Defence',
    'Positioning',
    'Close outs',
    'Zone defence',
    'Marked defence',
    'Tackling',
    'Tracking',
    'Picks',
    'Hand offs',
    'Cuts',
    'Shooting',
    'Ball carrying',
    'Decision making',
    'Catching (chasers)',
    'Catching (beaters)',
    'Dodgeball blocks',
    'Throwbacks',
    'Dodging',
    'Throwing',
    'Reaction time',
    'Strips',
    '2-2',
    'Hoops/Bailor',
    'Interpositional',
    'Agility',
    'Speed',
    'Strength',
    'Wing',
    'Driving',
    'Communication',
    'Timing'
  ];