export const PREDEFINED_SKILLS = [
	'Passing',
	'Offence',
	'Defence',
	'Positioning',
	'Close Outs',
	'Zone Defence',
	'Marked Defence',
	'Tackling',
	'Tracking',
	'Picks',
	'Hand Offs',
	'Cuts',
	'Shooting',
	'Ball Carrying',
	'Decision Making',
	'Catching (Chasers)',
	'Catching (Beaters)',
	'Dodgeball Blocks',
	'Throwbacks',
	'Dodging',
	'Throwing',
	'Reaction Time',
	'Strips',
	'2-2',
	'Hoops/Baylor',
	'Interpositional',
	'Agility',
	'Speed',
	'Strength',
	'Wing',
	'Driving',
	'Communication',
	'Timing'
];
