"""empty message

Revision ID: d619d994ebdc
Revises: 
Create Date: 2024-08-20 10:45:23.902796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd619d994ebdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brief_description', sa.String(length=255), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('skill_level', sa.String(length=50), nullable=False),
    sa.Column('complexity', sa.String(length=50), nullable=True),
    sa.Column('suggested_length', sa.String(length=50), nullable=False),
    sa.Column('number_of_people', sa.Integer(), nullable=True),
    sa.Column('skills_focused_on', sa.PickleType(), nullable=False),
    sa.Column('positions_focused_on', sa.PickleType(), nullable=False),
    sa.Column('video_link', sa.String(length=255), nullable=True),
    sa.Column('images', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('practice_goals', sa.String(length=255), nullable=True),
    sa.Column('phase_of_season', sa.String(length=50), nullable=True),
    sa.Column('number_of_participants', sa.Integer(), nullable=True),
    sa.Column('level_of_experience', sa.String(length=50), nullable=True),
    sa.Column('skills_focused_on', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('time_per_drill', sa.String(length=50), nullable=True),
    sa.Column('breaks_between_drills', sa.String(length=50), nullable=True),
    sa.Column('total_practice_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_plan')
    op.drop_table('drill')
    # ### end Alembic commands ###
